eOverdracht Service Registration manual
nuts-foundation/nuts-workshops pull request #10
Opened 2021-09-21 14:16 UTC by reinkrul

2021-09-21 15:46 UTC, woutslakhorst requested changes

2021-09-21 15:46 UTC, woutslakhorst commented on eOverdracht/1-service-registration.md
> +After completing the steps in this manual your care organization can transfer patients to other care organizations, or receive transfers.
some more steps are required of course ;)

2021-09-21 15:46 UTC, woutslakhorst commented on eOverdracht/1-service-registration.md
> +* `oauth`: for requesting access tokens to access remote Nuts nodes. Required for both `eOverdracht-sender` and `eOverdracht-receiver`.
to access protected resource, not the node directly.

2021-09-21 15:46 UTC, woutslakhorst commented on eOverdracht/1-service-registration.md
> +In test/development setups the *Nuts Demo EHR* application will generally handle the notification, so replace `<external-ehr-address>` with the correct host/port so it can be reached by external EHRs
Weird sentence

2021-09-21 15:46 UTC, woutslakhorst commented on eOverdracht/1-service-registration.md
> +POST /internal/didman/v1/did/{did}/endpoint
I added `<internal-node-address>` before each path

2021-09-22 04:40 UTC, reinkrul commented on eOverdracht/1-service-registration.md
> +After completing the steps in this manual your care organization can transfer patients to other care organizations, or receive transfers.
I've remove the sentence

2021-09-22 06:02 UTC, woutslakhorst approved these changes

2021-09-23 06:48 UTC, merged