added authorization credential manual
nuts-foundation/nuts-workshops pull request #8
Opened 2021-09-21 07:43 UTC by woutslakhorst

2021-09-21 10:39 UTC, reinkrul requested changes

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +Authorization credentials have a `purposeOfUse` which scope the credential to a specific (part of a) Bolt.
scopes

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +Other nodes will not be able to view the credential.
which is currently not true

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +The credentials are issued to the actor, the care organization which users have a demand for patient data.
do we also need to state something about the subject (patient)?

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +The credentials are issued by the custodian, the care organization that is responsible for the data that is to be shared.
"holder of the data"?

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +The example above describes an authorization credential that is created by the *sender* of the *eOverdracht* bolt.
sender of the *eOverdracht* transfer

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +It also allows the recipient to read and perform the FHIR *document* operation on the specified composition.
read -> *read*

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +POST <internal-node-address>/internal/vcr/v1/authorization?untrusted=true
ouch, maybe we should provide some handy JSON Path-enabled API for this in the future for easier querying.

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +POST <internal-node-address>/internal/vcr/v1/authorization?untrusted=true
do we need to explain `untrusted=true`?

2021-09-21 10:39 UTC, reinkrul commented on mini-manuals/5-authz-credentials.md
> +## Description
I'm missing something either in the Description section or at the bottom as conclusion, what the result is of this manual ("and now you can do XYZ, next follow manual ABC")

2021-09-21 13:24 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +Other nodes will not be able to view the credential.
don't tell anyone

2021-09-21 13:25 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +The credentials are issued to the actor, the care organization which users have a demand for patient data.
we haven't implemented it in the demo, so we'll just skip it for now.

2021-09-21 13:28 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +The example above describes an authorization credential that is created by the *sender* of the *eOverdracht* bolt.
I was actually referring to the role within the bolt

2021-09-21 13:28 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +The credentials are issued by the custodian, the care organization that is responsible for the data that is to be shared.
made it even shorter.

2021-09-21 13:31 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +POST <internal-node-address>/internal/vcr/v1/authorization?untrusted=true
```
{
    "credentialSubject.id": "did:nuts:JCJEi3waNGNhkmwVvFB3wdUsmDYPnTcZxYiWThZqgWKv"
}
```

would already be better.

2021-09-21 13:32 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +POST <internal-node-address>/internal/vcr/v1/authorization?untrusted=true
we do this in the presentation

2021-09-21 13:33 UTC, woutslakhorst commented on mini-manuals/5-authz-credentials.md
> +## Description
I think we'll add that to the specific workshop READMEs. Start with 1,2,3 and maybe do 4

2021-09-22 04:39 UTC, reinkrul approved these changes

2021-09-22 06:00 UTC, merged